# Generated by Django 4.2.7 on 2023-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitetype',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
